In [1]:
print('Hello World')

Hello World

# 1st Lesson: Variables in Python

In [2]:
y = 'Mint Chocolate Chip'
print(y)

Mint Chocolate Chip

In [3]:
type(y)

str

In [1]:
y = 'Chocolate' 
Y = 'Mint Chocolate Chip'
print(y)
print(Y)

Chocolate
Mint Chocolate Chip

In [2]:
y = 'Chocolate' 
y = 'Mint Chocolate Chip'
print(y)

Mint Chocolate Chip

In [3]:
x, y, z, = 'Chocolate', 'Vanilla', 'Rocky Road'
print(x)
print(y)
print(z)

Chocolate
Vanilla
Rocky Road

In [4]:
x = y = z = 'Chocolate'
print(x)
print(y)
print(z)

Chocolate
Chocolate
Chocolate

In [6]:
ice_cream = ['chocolate', 'vanilla', 'rocky road']
print(ice_cream)

x,y,z = ice_cream
print(x)
print(y)
print(z)

['chocolate', 'vanilla', 'rocky road']
chocolate
vanilla
rocky road

Variable Naming

In [ ]:
# Camel Case
# Test Variable Case
testVariableCase = 'Vanilla Swirl'

In [ ]:
# Pascal Case
# Test Variable Case
TestVariableCase = 'Vanilla Swirl'

In [ ]:
# For the most part, this is the best way to name a variable
# Snake Case
# Test Variable Case
test_variable_case = 'Vanilla Swirl'

In [8]:
x = 'Ice cream is the best' + '.'
print(x)
# x = 'Ice cream is the best' + 2 <-- this is not allowed because the type of variables must match

Ice cream is the best.

In [9]:
x = 1
y = 2
z = 3

print(x+y+z)

6

In [10]:
x = 'i love baseball'
y = 3
print(x,y) 
# You are allowed to print different data types together as long as 
# they are separated via commas

i love baseball 3

# Data Types

In [12]:
x = type(-12)
y = type(10.1) 
z = type(3j) #only j works for complex numbers, there is no e or i, etc
print(x, y, z)

<class 'int'> <class 'float'> <class 'complex'>

In [2]:
# Strings
# you can do single, double, or triple quote

a = 'single quote'
b = "double quote"
# single and double quotes work for single-line us; the difference is that if you need a quote for
# a word such as I've or shouldn't, you should encase your string with double quotes because you will
# encounter an error if you try to use single quote encasing with a compound word
# triple quotes are used for strings that span multiple lines, and you can use single or double quotes 
# However, you may not use triple quotes within said triple quote
c = """
Girl, it's easy to love me now
Would you love me if I was down and out?
Would you still have love for me?
Girl, it's easy to love me now
Would you love me if I was down and out?
Would you still have love for me?
"""
type(a)
type(b)
type(c)

str

In [5]:
# You can pull specific characters and words from a string using the variable name
# as an array, a[:6] calls for the first 6 characters of string a
print(a[:6])
print(b[6:12]) # another example, you can start from anywhere, not just the beginning

single
 quote

In [6]:
# Lists
[1,2,3]

[1, 2, 3]

In [7]:
['Chapman', 'Devers', 'Adames']

['Chapman', 'Devers', 'Adames']

In [10]:
# This is known as a nested list because there is a list within a list
['3B', ['DH', '1B'], 'SS']

['3B', ['DH', '1B'], 'SS']

In [14]:
giants_players = ['Chapman', 'Devers', 'Adames']
giants_player_positions = ['3B', ['DH', '1B'], 'SS']
print(giants_players)
print(giants_player_positions)
giants_players.append('Ramos')
giants_player_positions.append('LF')
print(giants_players)
print(giants_player_positions)

['Chapman', 'Devers', 'Adames']
['3B', ['DH', '1B'], 'SS']
['Chapman', 'Devers', 'Adames', 'Ramos']
['3B', ['DH', '1B'], 'SS', 'LF']

In [15]:
print(giants_players)
print(giants_player_positions)
giants_players[0] = 'Arraez'
giants_player_positions[0] = '2B'
print(giants_players)
print(giants_player_positions)

['Chapman', 'Devers', 'Adames', 'Ramos']
['3B', ['DH', '1B'], 'SS', 'LF']
['Arraez', 'Devers', 'Adames', 'Ramos']
['2B', ['DH', '1B'], 'SS', 'LF']

In [17]:
# Tuple
# Tuples may be useful in some cases, however, in most cases it's not because we 
# can not change the data that is stored within the tuple, in cases where data can
# be stored and no change then tuples can be useful but that is the only case
tuple = (1,2,4,5)
print(type(tuple))
print(tuple[2])

<class 'tuple'>
4

In [21]:
# Sets
# Similar to lists and tuples, one big difference is that they do not carry
# duplicate values and values can not be accessed through indexes because 
# sets are unordered, they can be accessed through loops
daily_pints = [1,2,3]
print(type(daily_pints))
print(daily_pints)

<class 'list'>
[1, 2, 3]

In [4]:
# example of sets only showing unique values even if you assign it with duplicates
num_set = {1,2,3,4,5,6,5,3,1} 
num_set_two = {4,5,6,7,8,9,6,5,7}
print(num_set)
print(num_set_two)

{1, 2, 3, 4, 5, 6}
{4, 5, 6, 7, 8, 9}

In [5]:
# functions you can perform on sets
print(num_set | num_set_two) # this takes the combined unique values between the two sets
print(num_set & num_set_two) # this shows the matching values of both sets 
print(num_set - num_set_two) # this eliminates the shared values between both sets and 
                             # displays what's left of the first set
print(num_set ^ num_set_two) # this is going to show the values that are unique between both sets altogether

{1, 2, 3, 4, 5, 6, 7, 8, 9}
{4, 5, 6}
{1, 2, 3}
{1, 2, 3, 7, 8, 9}

In [7]:
# Dictionaries
# This data type will hold a key/value pair where the key categorizes the value

giants_players = {'name':'Jung Hoo Lee', 'position':['CF', 'RF'], 'bats':'L'}
print(type(giants_players))
print(giants_players.values())
print(giants_players.keys())

<class 'dict'>
dict_values(['Jung Hoo Lee', ['CF', 'RF'], 'L'])
dict_keys(['name', 'position', 'bats'])

In [9]:
# With dictonaries you can not call the values through indexes such as [0]
# We call these like this 
giants_players['name']

'Jung Hoo Lee'

In [12]:
# we are allowed to update the values we can do this by
giants_players['name'] = 'Matt Chapman'
print(giants_players)
giants_players.update({'name':'Matt Chapman', 'position':'3B', 'bats':'R'})
print(giants_players)

{'name': 'Matt Chapman', 'position': ['CF', 'RF'], 'bats': 'L'}
{'name': 'Matt Chapman', 'position': '3B', 'bats': 'R'}

In [13]:
# we can delete keys and the values along with it via
del giants_players['bats']
print(giants_players)

{'name': 'Matt Chapman', 'position': '3B'}

# Comparison Operators

In [14]:
10 == 10

True

In [15]:
10 == 50

False

In [16]:
10 != 50

True

In [17]:
'Vanilla' == 'Vanilla'

True

In [18]:
x = 'giants'
y = 'dodgers'
x != y

True

In [19]:
10 <= 10

True

In [20]:
10 >= 10

True

# Logical Operators

In [ ]:
# and this will return true if both sides are true
# or will return true if one side or the other is true
# not reverses the returned result t.f. true --> false and false --> true

In [21]:
(10 < 50) and (25 > 5)

True

In [22]:
(10 > 50) and (25 > 5)

False

In [24]:
(10 > 50) or (25 > 5)

True

In [26]:
not ((10 > 50) or (25 > 5)) # not reverses true into false

False

# Membership Operator

In [27]:
# in --> returns TRUE if a sequence with a specified valuye is present in the object
# not in --> returns TRUE if a sequence with the specified value is not present in the object

In [28]:
giants_players = 'Chapman Devers Lee Bader Webb'
'Devers' in giants_players

True

In [29]:
numbers = [1,2,3,4,5]
num1 = 9
num1 not in numbers

True

# If, Elif, Else Statements

In [30]:
if 25 > 10:
    print('It worked')

It worked

In [31]:
if 25 < 10:
    print('It worked')
else:
    print('It did not work')

It did not work

In [32]:
if 25 < 10:
    print('It worked')
elif 25 < 30:
    print('elif worked')
else:
    print('It did not work')

elif worked

In [33]:
if 25 < 10:
    print('It worked')
elif 25 > 30:
    print('elif 1 worked')
elif 10 == 11:
    print('elif 2 worked')
elif 15 > 11:
    print('elif 3 worked')
else:
    print('It did not work')

elif 3 worked

In [34]:
if 25 > 10:
    print('It worked')
    if 5 == 5:
        print('nested if worked')
elif 25 > 30:
    print('elif 1 worked')
elif 10 == 11:
    print('elif 2 worked')
elif 15 > 11:
    print('elif 3 worked')
else:
    print('It did not work')

It worked
nested if worked

# For Loops

In [35]:
integers = [1,2,3,4,5,6]
for numbers in integers: 
    print(numbers)

1
2
3
4
5
6

In [36]:
for numbers in integers: 
    print(numbers + numbers)

2
4
6
8
10
12

In [38]:
giants_players = {'name':'Jung Hoo Lee', 'position':['CF', 'RF'], 'bats':'L'}
for info in giants_players.values(): # we have the .values to specify we want the values
    print(info)

Jung Hoo Lee
['CF', 'RF']
L

In [39]:
for key, value in giants_players.items():
    print(key, ' -> ',value)

name  ->  Jung Hoo Lee
position  ->  ['CF', 'RF']
bats  ->  L

# Nested For Loop

In [42]:
player = ['Ohtani', 'Devers', 'Tatis Jr']
hits = ['single', 'double', 'triple', 'homerun']

for name in player:
    for _type in hits:
        print(name, ' hit a ', _type)

Ohtani  hit a  single
Ohtani  hit a  double
Ohtani  hit a  triple
Ohtani  hit a  homerun
Devers  hit a  single
Devers  hit a  double
Devers  hit a  triple
Devers  hit a  homerun
Tatis Jr  hit a  single
Tatis Jr  hit a  double
Tatis Jr  hit a  triple
Tatis Jr  hit a  homerun

# While Loop

In [43]:
num = 0
while num < 4:
    print(num)
    num = num + 1

0
1
2
3

In [44]:
num = 0
while num < 4:
    print(num)
    if num == 2:
        break # exits the loop if the condition is met
    num = num + 1

0
1
2

In [45]:
# continue is another word you may use, when it is called the block of code its 
# in will stop and restart from the top of the loop

# Functions

In [47]:
def first_func():
    print('We did it')

In [48]:
first_func()

We did it

In [49]:
def number_squared(number):
    print(number**2)

In [50]:
number_squared(4)

16

In [52]:
def num_squared_cust(number, power):
    print(number**power)

In [53]:
num_squared_cust(5,3)

125

In [4]:
# You can make an arbitrary argument; this is 
# useful if you are not sure how many arguments 
# you'll enter into the function
def number_args(*number): # *number marks the arbitrary argument
    print(number[0]*number[1])

In [7]:
# With the 5 inputs, we still only use the first two
number_args(7,6,5,2,4)

42

In [9]:
# We can also pass a tuple, like this
num_tuple = (7,6,5,2,4)
number_args(*num_tuple)

42

In [11]:
# keyword argument --> **name_of_variable
def number_kwarg(**number):
    print('My number is: ' + number['integer'] + ' My other number: ' + number['integer2'])

In [12]:
# we create the keywords via the argument, shown below
number_kwarg(integer = '4121', integer2 = '1091')

My number is: 4121 My other number: 1091

# Converting Data Types

In [13]:
num_int = 7
type(num_int)

int

In [14]:
num_str = '75'
type(num_str)

str

In [16]:
con_num_str = int(num_str)
total = num_int + con_num_str
print(total)

82

In [18]:
list_type = [1,2,3]
type(list_type)

list

In [23]:
# converting from list to tuple, doesn't change the data as a tuple is just an unordered list
type(tuple(list_type))

tuple

In [25]:
# Converting the list to a set changes the data as the set only keeps the unique values
list_type = [1,2,3,4,4,6,7,8,9,0,2,5,3,10]
set(list_type)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [4]:
sfgiants_dict = {'name': 'Willy','Bats':'R','Throws':'R'}
type(sfgiants_dict)

dict

In [5]:
sfgiants_dict.items()

dict_items([('name', 'Willy'), ('Bats', 'R'), ('Throws', 'R')])

In [6]:
sfgiants_dict.keys()

dict_keys(['name', 'Bats', 'Throws'])

In [8]:
sfgiants_dict.values()

dict_values(['Willy', 'R', 'R'])

In [9]:
# We can turn dictionaries into lists however only separately as keys and values
type(list(sfgiants_dict.keys()))

list

In [10]:
type(list(sfgiants_dict.values()))

list

In [12]:
# strings to lists and sets
str1 = 'i wanna party'
list(str1)

['i', ' ', 'w', 'a', 'n', 'n', 'a', ' ', 'p', 'a', 'r', 't', 'y']

In [13]:
set(str1)

{' ', 'a', 'i', 'n', 'p', 'r', 't', 'w', 'y'}

# BMI Calculator

In [ ]:
# BMI = WEIGHT (LBS) * 703 / HEIGHT *HEIGHT (IN)

In [17]:
name = input("Enter your name: ")
weight = int(input("Enter your weight in pounds: "))

height = int(input("Enter your height in inches: "))

bmi = (weight * 703) / (height * height)

print('Your BMI is: ', bmi)
if bmi > 0:
    if(bmi > 18.5):
        print(name + ", you are underweight.")
    elif(bmi <= 24.5):
        print(name + ", you are normal weight.")
    elif(bmi < 29.9):
        print(name + ", you are overweight.")
    elif(bmi < 34.9):
        print(name + ", you are obese.")
    elif(bmi < 39.9):
        print(name + ", you are severly obese.")
    else:
        print(name + ", you are morbidly obese.")
else:
    print("Enter valid input")

Enter your weight in pounds:  258
Enter your height in inches:  78

Your BMI is:  29.81163708086785

# BeautifulSoup and Requests

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url = 'https://www.scrapethissite.com/pages/forms/'

In [7]:
page = requests.get(url)

In [11]:
# Response of 200 is good, other codes means there is an error
soup = BeautifulSoup(page.text, 'html')
# stores all the HTML code of our URL, and the '.text' converts it into text form
print(soup)

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

In [12]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.55
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        292
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        344
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        49
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.613
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        211
       </td>
       <td class="diff text-success">
        73
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        298
       </td>
       <td class="diff text-danger">
        -25
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        272
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        238
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-danger">
        -38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        340
       </td>
       <td class="ga">
        254
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.338
       </td>
       <td class="gf">
        256
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        249
       </td>
       <td class="diff text-success">
        24
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.312
       </td>
       <td class="gf">
        223
       </td>
       <td class="ga">
        290
       </td>
       <td class="diff text-danger">
        -67
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        297
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        267
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        342
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.2
       </td>
       <td class="gf">
        236
       </td>
       <td class="ga">
        354
       </td>
       <td class="diff text-danger">
        -118
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        22
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.588
       </td>
       <td class="gf">
        310
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.287
       </td>
       <td class="gf">
        241
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -77
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        28
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.35
       </td>
       <td class="gf">
        243
       </td>
       <td class="ga">
        315
       </td>
       <td class="diff text-danger">
        -72
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        258
       </td>
       <td class="ga">
        258
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        260
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-danger">
        -5
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        296
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        257
       </td>
       <td class="ga">
        236
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">
          18
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=19">
          19
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=20">
          20
         </a>

# Find and Find_all

In [16]:
# Using info from previous lines such as page, url, etc.
# this line find the first div among the html code
soup.find('div')

<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>

In [17]:
# find_all will get all instances of what we were trying to look for in this example it would be div
soup.find_all('div')

[<div class="container">
 <div class="col-md-12">
 <ul class="nav nav-tabs">
 <li id="nav-homepage">
 <a class="nav-link hidden-sm hidden-xs" href="/">
 <img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                 Scrape This Site
                             </a>
 </li>
 <li id="nav-sandbox">
 <a class="nav-link" href="/pages/">
 <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                 Sandbox
                             </a>
 </li>
 <li id="nav-lessons">
 <a class="nav-link" href="/lessons/">
 <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                 Lessons
                             </a>
 </li>
 <li id="nav-faq">
 <a class="nav-link" href="/faq/">
 <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                 FAQ
                             </a>
 </li>
 <li class="pull-right" id="nav-login">
 <a class="nav-link" href="/login/">
                                 Login
                             </a>
 </li>
 </ul>
 </div>
 </div>,
 <div class="col-md-12">
 <ul class="nav nav-tabs">
 <li id="nav-homepage">
 <a class="nav-link hidden-sm hidden-xs" href="/">
 <img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                 Scrape This Site
                             </a>
 </li>
 <li id="nav-sandbox">
 <a class="nav-link" href="/pages/">
 <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                 Sandbox
                             </a>
 </li>
 <li id="nav-lessons">
 <a class="nav-link" href="/lessons/">
 <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                 Lessons
                             </a>
 </li>
 <li id="nav-faq">
 <a class="nav-link" href="/faq/">
 <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                 FAQ
                             </a>
 </li>
 <li class="pull-right" id="nav-login">
 <a class="nav-link" href="/login/">
                                 Login
                             </a>
 </li>
 </ul>
 </div>,
 <div id="page">
 <section id="hockey">
 <div class="container">
 <div class="row">
 <div class="col-md-12">
 <h1>
                             Hockey Teams: Forms, Searching and Pagination
                             <small>25 items</small>
 </h1>
 <hr/>
 </div>
 </div>
 <div class="row">
 <div class="col-md-12">
 <p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>
 <hr/>
 </div>
 </div>
 <div class="row">
 <div class="col-md-6">
 <p>
 <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                         </p>
 <hr/>
 </div>
 <div class="col-md-6 text-right">
 <p>

                                 Data via
                                 <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
 </p>
 <hr/>
 </div>
 </div>
 <div class="row search-area">
 <div class="col-md-12 text-center">
 <form action="/pages/forms/" class="form form-inline" method="GET">
 <label for="q">
                                 Search for Teams:
                             </label>
 <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
 <input class="btn btn-primary" type="submit" value="Search"/>
 </form>
 <hr/>
 </div>
 </div><!--.row.search-area-->
 <table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.55
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             292
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             344
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             49
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.613
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             211
                         </td>
 <td class="diff text-success">
                             73
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             298
                         </td>
 <td class="diff text-danger">
                             -25
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             272
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             238
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-danger">
                             -38
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             340
                         </td>
 <td class="ga">
                             254
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.338
                         </td>
 <td class="gf">
                             256
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             249
                         </td>
 <td class="diff text-success">
                             24
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             8
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.312
                         </td>
 <td class="gf">
                             223
                         </td>
 <td class="ga">
                             290
                         </td>
 <td class="diff text-danger">
                             -67
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             297
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             32
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             267
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             342
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.2
                         </td>
 <td class="gf">
                             236
                         </td>
 <td class="ga">
                             354
                         </td>
 <td class="diff text-danger">
                             -118
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             22
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.588
                         </td>
 <td class="gf">
                             310
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.287
                         </td>
 <td class="gf">
                             241
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -77
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             28
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.35
                         </td>
 <td class="gf">
                             243
                         </td>
 <td class="ga">
                             315
                         </td>
 <td class="diff text-danger">
                             -72
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             258
                         </td>
 <td class="ga">
                             258
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             26
                         </td>

In [19]:
# we can narrow our search with using class names along with the tag
soup.find_all('div', class_ = 'col-md-12')

[<div class="col-md-12">
 <ul class="nav nav-tabs">
 <li id="nav-homepage">
 <a class="nav-link hidden-sm hidden-xs" href="/">
 <img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                 Scrape This Site
                             </a>
 </li>
 <li id="nav-sandbox">
 <a class="nav-link" href="/pages/">
 <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                 Sandbox
                             </a>
 </li>
 <li id="nav-lessons">
 <a class="nav-link" href="/lessons/">
 <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                 Lessons
                             </a>
 </li>
 <li id="nav-faq">
 <a class="nav-link" href="/faq/">
 <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                 FAQ
                             </a>
 </li>
 <li class="pull-right" id="nav-login">
 <a class="nav-link" href="/login/">
                                 Login
                             </a>
 </li>
 </ul>
 </div>,
 <div class="col-md-12">
 <h1>
                             Hockey Teams: Forms, Searching and Pagination
                             <small>25 items</small>
 </h1>
 <hr/>
 </div>,
 <div class="col-md-12">
 <p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>
 <hr/>
 </div>,
 <div class="col-md-12 text-center">
 <form action="/pages/forms/" class="form form-inline" method="GET">
 <label for="q">
                                 Search for Teams:
                             </label>
 <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
 <input class="btn btn-primary" type="submit" value="Search"/>
 </form>
 <hr/>
 </div>,
 <div class="col-md-12 text-center text-muted">
                     Lessons and Videos © Hartley Brody 2023
                 </div>]

In [21]:
# When we want to pull info and turn it into text, we need to use find and if we try and use find_all we will
# get an error
soup.find('p', class_ = 'lead').text

'\n                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.\n                        '

In [23]:
# We can pull information from tables that on the site we are webscraping from, here is an example of how to pull
# info from the website stored in url
soup.find_all('th')
# the above line pulls the table categories

[<th>
                             Team Name
                         </th>,
 <th>
                             Year
                         </th>,
 <th>
                             Wins
                         </th>,
 <th>
                             Losses
                         </th>,
 <th>
                             OT Losses
                         </th>,
 <th>
                             Win %
                         </th>,
 <th>
                             Goals For (GF)
                         </th>,
 <th>
                             Goals Against (GA)
                         </th>,
 <th>
                             + / -
                         </th>]

In [24]:
soup.find('th').text

'\n                            Team Name\n                        '

In [25]:
soup.find('th').text.strip()

'Team Name'

In [26]:
# above lines takes the first th and reduce it to a string

# Scraping Data from a Real Website + Pandas

In [38]:
from bs4 import BeautifulSoup
import requests
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
}

page = requests.get(url, headers=headers)

soup = BeautifulSoup(page.text, "html")

print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies in the United States by revenue - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f86886bb-5e07-41f3-91f8-690a354adb83","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgTitle":"List of largest companies in the United States by revenue","wgCurRevisionId":1354288064,"wgRevisionId":1354288064,"wgArticleId":61181662,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use mdy dates from April 2025","Economy of the United States-related lists","Lists of companies by revenue","Lists of largest private companies by country","Lists of companies of the United States"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgRelevantArticleId":61181662,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":false,"wgWikibaseItemId":"Q1860802","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.2" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies in the United States by revenue - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <link href="auth.wikimedia.org" rel="dns-prefetch"/>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_United_States_by_revenue rootpage-List_of_largest_companies_in_the_United_States_by_revenue skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item user-links-collapsible-item" id="pt-sitesupport-2">
           <a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item user-links-collapsible-item" id="pt-createaccount-2">
           <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory">
            <span>
             Create account
            </span>
           </a>
          </li>
          <li class="mw-list-item user-links-collapsible-item" id="pt-login-2">

In [34]:
print(soup)

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest companies in the United States by revenue - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f86886bb-5e07-41f3-91f8-690a354adb83","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgTitle":"List of largest companies in the United States by revenue","wgCurRevisionId":1354288064,"wgRevisionId":1354288064,"wgArticleId":61181662,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use mdy dates from April 2025","Economy of the United States-related lists","Lists of companies by revenue","Lists of largest private companies by country","Lists of companies of the United States"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgRelevantArticleId":61181662,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":false,"wgWikibaseItemId":"Q1860802","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.2" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest companies in the United States by revenue - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_United_States_by_revenue rootpage-List_of_largest_companies_in_the_United_States_by_revenue skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item user-links-collapsible-item" id="pt-sitesupport"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart"></span>
<span>Donate</span></a>
</li>
<li class="mw-list-item user-links-collapsible-item" id="pt-createaccount"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span>
<span>Create account</span></a>
</li>
<li class="mw-list-item user-links-collapsible-item" id="pt-login"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span>
<span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">
<div class="vector-sitenotice-container">
<div id="siteNotice"><!-- CentralNotice --></div>
</div>

In [39]:
# We want to pull info from the tables so we are searching through all the tables to find the one we want
soup.find_all('table')

[<table class="wikitable sortable">
 <caption>
 </caption>
 <tbody><tr>
 <th>Rank
 </th>
 <th>Name
 </th>
 <th>Industry
 </th>
 <th>Revenue <br/>(USD millions)
 </th>
 <th>Revenue growth
 </th>
 <th>Employees
 </th>
 <th>Headquarters
 </th></tr>
 <tr>
 <td>1
 </td>
 <td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">680,985
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
 </td>
 <td style="text-align:center;">2,100,000
 </td>
 <td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
 </td></tr>
 <tr>
 <td>2
 </td>
 <td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
 </td>
 <td>Retail and cloud computing
 </td>
 <td style="text-align:center;">637,959
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
 </td>
 <td style="text-align:center;">1,556,000
 </td>
 <td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
 </td></tr>
 <tr>
 <td>3
 </td>
 <td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">400,278
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
 </td>
 <td style="text-align:center;">400,000
 </td>
 <td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
 </td></tr>
 <tr>
 <td>4
 </td>
 <td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
 </td>
 <td>Technology
 </td>
 <td style="text-align:center;">391,035
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
 </td>
 <td style="text-align:center;">164,000
 </td>
 <td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
 </td></tr>
 <tr>
 <td>5
 </td>
 <td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">372,809
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
 </td>
 <td style="text-align:center;">259,500
 </td>
 <td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
 </td></tr>
 <tr>
 <td>6
 </td>
 <td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
 </td>
 <td>Conglomerate
 </td>
 <td style="text-align:center;">371,433
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
 </td>
 <td style="text-align:center;">392,400
 </td>
 <td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
 </td></tr>
 <tr>
 <td>7
 </td>
 <td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">350,018
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
 </td>
 <td style="text-align:center;">183,323
 </td>
 <td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
 </td></tr>
 <tr>
 <td>8
 </td>
 <td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
 </td>
 <td>Petroleum
 </td>
 <td style="text-align:center;">349,595
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
 </td>
 <td style="text-align:center;">60,900
 </td>
 <td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
 </td></tr>
 <tr>
 <td>9
 </td>
 <td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">308,951
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
 </td>
 <td style="text-align:center;">48,000
 </td>
 <td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
 </td></tr>
 <tr>
 <td>10
 </td>
 <td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
 </td>
 <td>Pharmacy wholesale
 </td>
 <td style="text-align:center;">293,959
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
 </td>
 <td style="text-align:center;">44,000
 </td>
 <td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
 </td></tr>
 <tr>
 <td>11
 </td>
 <td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">278,906
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
 </td>
 <td style="text-align:center;">317,233
 </td>
 <td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
 </td></tr>
 <tr>
 <td>12
 </td>
 <td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">254,453
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
 </td>
 <td style="text-align:center;">333,000
 </td>
 <td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
 </td></tr>
 <tr>
 <td>13
 </td>
 <td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
 </td>
 <td>Health insurance
 </td>
 <td style="text-align:center;">247,121
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
 </td>
 <td style="text-align:center;">72,398
 </td>
 <td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
 </td></tr>
 <tr>
 <td>14
 </td>
 <td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">245,122
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
 </td>
 <td style="text-align:center;">228,000
 </td>
 <td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
 </td></tr>
 <tr>
 <td>15
 </td>
 <td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">226,827
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
 </td>
 <td style="text-align:center;">48,411
 </td>
 <td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
 </td></tr>
 <tr>
 <td>16
 </td>
 <td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
 </td>
 <td>Petroleum
 </td>
 <td style="text-align:center;">202,792
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
 </td>
 <td style="text-align:center;">45,298
 </td>
 <td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
 </td></tr>
 <tr>
 <td>17
 </td>
 <td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">192,434
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
 </td>
 <td style="text-align:center;">213,193
 </td>
 <td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
 </td></tr>
 <tr>
 <td>18
 </td>
 <td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
 </td>
 <td>Automotive
 </td>
 <td style="text-align:center;">187,442
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
 </td>
 <td style="text-align:center;">162,000
 </td>
 <td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
 </td></tr>
 <tr>
 <td>19
 </td>
 <td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
 </td>
 <td>Automotive
 </td>
 <td style="text-align:center;">184,992
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
 </td>
 <td style="text-align:center;">171,000
 </td>
 <td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
 </td></tr>
 <tr>
 <td>20
 </td>
 <td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">177,011
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
 </td>
 <td style="text-align:center;">103,679
 </td>

In [41]:
soup.find_all('table')[1]

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD billions)
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Cargill" title="Cargill">Cargill</a>
</td>
<td>Food &amp; Drink
</td>
<td style="text-align:center;">154
</td>
<td style="text-align:center;">155,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>2
</td>
<td><a class="mw-redirect" href="/wiki/Koch_Industries" title="Koch Industries">Koch</a>
</td>
<td>Multicompany
</td>
<td style="text-align:center;">125
</td>
<td style="text-align:center;">120,000
</td>
<td><a href="/wiki/Wichita,_Kansas" title="Wichita, Kansas">Wichita, Kansas</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Publix_Super_Markets" title="Publix Super Markets">Publix Super Markets</a>
</td>
<td>Food Markets
</td>
<td style="text-align:center;">59.7
</td>
<td style="text-align:center;">260,000
</td>
<td><a href="/wiki/Lakeland,_Florida" title="Lakeland, Florida">Lakeland, Florida</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Mars,_Incorporated" title="Mars, Incorporated">Mars</a>
</td>
<td>Food &amp; Drink
</td>
<td style="text-align:center;">55
</td>
<td style="text-align:center;">150,000
</td>
<td><a href="/wiki/McLean,_Virginia" title="McLean, Virginia">McLean, Virginia</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/H-E-B" title="H-E-B">H-E-B Grocery Company</a>
</td>
<td>Food Markets
</td>
<td style="text-align:center;">49.57
</td>
<td style="text-align:center;">175,000
</td>
<td><a class="mw-redirect" href="/wiki/San_Antonio,_Texas" title="San Antonio, Texas">San Antonio, Texas</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Reyes_Holdings" title="Reyes Holdings">Reyes Holdings</a>
</td>
<td>Food, Drink &amp; Tobacco
</td>
<td style="text-align:center;">44
</td>
<td style="text-align:center;">36,000
</td>
<td><a href="/wiki/Rosemont,_Illinois" title="Rosemont, Illinois">Rosemont, Illinois</a>
</td></tr>
<tr>
<td>7
</td>
<td><a class="mw-redirect" href="/wiki/Enterprise_Mobility" title="Enterprise Mobility">Enterprise Mobility</a>
</td>
<td>Services
</td>
<td style="text-align:center;">38
</td>
<td style="text-align:center;">100,000
</td>
<td><a href="/wiki/Clayton,_Missouri" title="Clayton, Missouri">Clayton, Missouri</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/Fidelity_Investments" title="Fidelity Investments">Fidelity Investments</a>
</td>
<td>Insurance
</td>
<td style="text-align:center;">32.7
</td>
<td style="text-align:center;">78,000
</td>
<td><a href="/wiki/Boston" title="Boston">Boston, Massachusetts</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/Southern_Glazer%27s_Wine_and_Spirits" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine &amp; Spirits</a>
</td>
<td>Food, Drink &amp; Tobacco
</td>
<td style="text-align:center;">25
</td>
<td style="text-align:center;">24,000
</td>
<td><a href="/wiki/Miramar,_Florida" title="Miramar, Florida">Miramar, Florida</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cox_Enterprises" title="Cox Enterprises">Cox Enterprises</a>
</td>
<td>Media
</td>
<td style="text-align:center;">23.5
</td>
<td style="text-align:center;">50,000
</td>
<td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
</td></tr></tbody></table>

In [43]:
#<table class="wikitable sortable jquery-tablesorter">
#</table>
# in the above cell, we used 1 to specify we wanted the first table, here is another way to pull it using the
# class name
soup.find_all('table', class_ = 'wikitable sortable')

[<table class="wikitable sortable">
 <caption>
 </caption>
 <tbody><tr>
 <th>Rank
 </th>
 <th>Name
 </th>
 <th>Industry
 </th>
 <th>Revenue <br/>(USD millions)
 </th>
 <th>Revenue growth
 </th>
 <th>Employees
 </th>
 <th>Headquarters
 </th></tr>
 <tr>
 <td>1
 </td>
 <td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">680,985
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
 </td>
 <td style="text-align:center;">2,100,000
 </td>
 <td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
 </td></tr>
 <tr>
 <td>2
 </td>
 <td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
 </td>
 <td>Retail and cloud computing
 </td>
 <td style="text-align:center;">637,959
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
 </td>
 <td style="text-align:center;">1,556,000
 </td>
 <td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
 </td></tr>
 <tr>
 <td>3
 </td>
 <td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">400,278
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
 </td>
 <td style="text-align:center;">400,000
 </td>
 <td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
 </td></tr>
 <tr>
 <td>4
 </td>
 <td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
 </td>
 <td>Technology
 </td>
 <td style="text-align:center;">391,035
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
 </td>
 <td style="text-align:center;">164,000
 </td>
 <td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
 </td></tr>
 <tr>
 <td>5
 </td>
 <td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">372,809
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
 </td>
 <td style="text-align:center;">259,500
 </td>
 <td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
 </td></tr>
 <tr>
 <td>6
 </td>
 <td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
 </td>
 <td>Conglomerate
 </td>
 <td style="text-align:center;">371,433
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
 </td>
 <td style="text-align:center;">392,400
 </td>
 <td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
 </td></tr>
 <tr>
 <td>7
 </td>
 <td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">350,018
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
 </td>
 <td style="text-align:center;">183,323
 </td>
 <td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
 </td></tr>
 <tr>
 <td>8
 </td>
 <td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
 </td>
 <td>Petroleum
 </td>
 <td style="text-align:center;">349,595
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
 </td>
 <td style="text-align:center;">60,900
 </td>
 <td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
 </td></tr>
 <tr>
 <td>9
 </td>
 <td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">308,951
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
 </td>
 <td style="text-align:center;">48,000
 </td>
 <td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
 </td></tr>
 <tr>
 <td>10
 </td>
 <td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
 </td>
 <td>Pharmacy wholesale
 </td>
 <td style="text-align:center;">293,959
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
 </td>
 <td style="text-align:center;">44,000
 </td>
 <td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
 </td></tr>
 <tr>
 <td>11
 </td>
 <td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">278,906
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
 </td>
 <td style="text-align:center;">317,233
 </td>
 <td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
 </td></tr>
 <tr>
 <td>12
 </td>
 <td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">254,453
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
 </td>
 <td style="text-align:center;">333,000
 </td>
 <td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
 </td></tr>
 <tr>
 <td>13
 </td>
 <td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
 </td>
 <td>Health insurance
 </td>
 <td style="text-align:center;">247,121
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
 </td>
 <td style="text-align:center;">72,398
 </td>
 <td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
 </td></tr>
 <tr>
 <td>14
 </td>
 <td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">245,122
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
 </td>
 <td style="text-align:center;">228,000
 </td>
 <td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
 </td></tr>
 <tr>
 <td>15
 </td>
 <td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">226,827
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
 </td>
 <td style="text-align:center;">48,411
 </td>
 <td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
 </td></tr>
 <tr>
 <td>16
 </td>
 <td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
 </td>
 <td>Petroleum
 </td>
 <td style="text-align:center;">202,792
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
 </td>
 <td style="text-align:center;">45,298
 </td>
 <td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
 </td></tr>
 <tr>
 <td>17
 </td>
 <td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">192,434
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
 </td>
 <td style="text-align:center;">213,193
 </td>
 <td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
 </td></tr>
 <tr>
 <td>18
 </td>
 <td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
 </td>
 <td>Automotive
 </td>
 <td style="text-align:center;">187,442
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
 </td>
 <td style="text-align:center;">162,000
 </td>
 <td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
 </td></tr>
 <tr>
 <td>19
 </td>
 <td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
 </td>
 <td>Automotive
 </td>
 <td style="text-align:center;">184,992
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
 </td>
 <td style="text-align:center;">171,000
 </td>
 <td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
 </td></tr>
 <tr>
 <td>20
 </td>
 <td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">177,011
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
 </td>
 <td style="text-align:center;">103,679
 </td>

In [64]:
# We make a variable to hold the data of just the first table
table = soup.find_all('table')[0]
print(table)

<table class="wikitable sortable">
<caption>
</caption>
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD millions)
</th>
<th>Revenue growth
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">680,985
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
</td>
<td style="text-align:center;">2,100,000
</td>
<td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
</td>
<td>Retail and cloud computing
</td>
<td style="text-align:center;">637,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
</td>
<td style="text-align:center;">1,556,000
</td>
<td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
</td></tr>
<tr>
<td>3
</td>
<td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">400,278
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
</td>
<td style="text-align:center;">400,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">391,035
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
</td>
<td style="text-align:center;">164,000
</td>
<td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">372,809
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
</td>
<td style="text-align:center;">259,500
</td>
<td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">371,433
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
</td>
<td style="text-align:center;">392,400
</td>
<td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
</td></tr>
<tr>
<td>7
</td>
<td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">350,018
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
</td>
<td style="text-align:center;">183,323
</td>
<td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">349,595
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
</td>
<td style="text-align:center;">60,900
</td>
<td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">308,951
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
</td>
<td style="text-align:center;">48,000
</td>
<td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
</td>
<td>Pharmacy wholesale
</td>
<td style="text-align:center;">293,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
</td>
<td style="text-align:center;">44,000
</td>
<td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">278,906
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
</td>
<td style="text-align:center;">317,233
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">254,453
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">333,000
</td>
<td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
</td></tr>
<tr>
<td>13
</td>
<td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
</td>
<td>Health insurance
</td>
<td style="text-align:center;">247,121
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
</td>
<td style="text-align:center;">72,398
</td>
<td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">245,122
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
</td>
<td style="text-align:center;">228,000
</td>
<td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">226,827
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
</td>
<td style="text-align:center;">48,411
</td>
<td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">202,792
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
</td>
<td style="text-align:center;">45,298
</td>
<td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">192,434
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
</td>
<td style="text-align:center;">213,193
</td>
<td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">187,442
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
</td>
<td style="text-align:center;">162,000
</td>
<td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">184,992
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">171,000
</td>
<td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">177,011
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
</td>
<td style="text-align:center;">103,679
</td>
<td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">170,757
</td>

In [65]:
# first step to get the category names, the names are under the tag 'th', i.e. we used find all 'th'
world_titles = table.find_all('th')
print(world_titles)

[<th>Rank
</th>, <th>Name
</th>, <th>Industry
</th>, <th>Revenue <br/>(USD millions)
</th>, <th>Revenue growth
</th>, <th>Employees
</th>, <th>Headquarters
</th>]

In [66]:
# now we are going to remove all the extra stuff around the names bc thats what we want
world_table_titles = [title.text.strip() for title in world_titles]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [54]:
import pandas as pd

In [67]:
df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [68]:
# there are two tags, one is the 'tr' that contains the entire row, but 'td' will contain the individual elements 
# of information we want and that is why we will use td and tr
column_data = table.find_all('tr')

In [70]:
# in the above cell we are using getting all the rows of data
# in this cell we are going through the rows and finding all the data and appending it to the dataframe
for row in column_data[1:]: # <-- [1:] was necessary because the 1st row was empty and throwing errors
    row_data = row.find_all('td') # <-- getting all the data throuhg td tags
    individual_row_data = [data.text.strip() for data in row_data] # <-- cleaning up the data
    # print(individual_row_data)
    length = len(df)
    df.loc[length] = individual_row_data

In [71]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [73]:
df.to_csv(r'C:\Users\chris\output for jupyter notebook\Companies.csv', index = False)